language: php

php:
  #- 5.4
  #- 5.5
  #- 5.6
  #- 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - php: 5.4
      dist: precise

sudo: false

before_script: composer install
script: phpunit Test.php
#script: ./build.sh