language: php

php:
  #- 5.4
  #- 5.5
  #- 5.6
  #- 7.0
  - 7.1
  - 7.2
  #- hhvm # on Trusty only
  #- nightly

matrix:
  include:
    - php: 5.5
      dist: precise

#sudo: false

before_script:
  - composer install
  - phpenv config-rm xdebug.ini

COMPOSER_ALLOW_XDEBUG=1

script: php ./vendor/bin/phpunit --UnitTest


#phpunit UnitTest
#script: ./build.sh